### ISSUE TITLE
add custom header 

### ISSUE THREAD

**Issue by alisharify7** [dillibk777/flask-helmet#1]
hi, 
this version of extension is added default header to each request in entire app
its not better to add a decorator or some to prevent some headers in some requests or routes?

for example :
when we initialize this extension it automatically add security headers to every request in app with @app.after_request middleware
     
it's not better to add a decorator like this:

@helmet.prevent(X-Powered-By=None)
@app.route("/")
      ....

and with this method developer can have more control over requests and routes

**Comment by dillibabukadati** [comment]
Thank you for your suggestion. It's a valid point, and adding a decorator to selectively prevent headers for specific requests or routes would indeed provide more control and flexibility to developers.

I appreciate your feedback, and I will take it into consideration for future improvements to the FlaskHelmet extension. It is now on my **todo** list, and I will work on implementing this feature to enhance the functionality of the extension.

Thank you for bringing this to my attention, and I aim to provide a better user experience with the extension based on your valuable input.
